In [ ]:
# !pip install -q numpy scikit-learn pandas matplotlib seaborn

In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler

# You can define your own functions here
def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

sns.set_theme(style="whitegrid")
plt.rcParams['figure.dpi'] = 110
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

In [8]:
# Open the dataset
data = pd.read_csv('auto-mpg.csv')
data.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl

In [9]:
# Understand the dataset
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    str
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    str
dtypes: float64(3), int64(4), str(2)
memory usage: 28.1 KB

In [10]:
# Clean the dataset
df_clean = (
    data.drop(columns=['origin', 'car name']) # Drop non-numeric columns
    .dropna() # Drop row with missing values
    .reset_index(drop=True) # Reset index after dropping rows
)
df_clean.head(10);

In [11]:
df_clean.head(10)

    mpg  cylinders  displacement horsepower  weight  acceleration  model year
0  18.0          8         307.0        130    3504          12.0          70
1  15.0          8         350.0        165    3693          11.5          70
2  18.0          8         318.0        150    3436          11.0          70
3  16.0          8         304.0        150    3433          12.0          70
4  17.0          8         302.0        140    3449          10.5          70
5  15.0          8         429.0        198    4341          10.0          70
6  14.0          8         454.0        220    4354           9.0          70
7  14.0          8         440.0        215    4312           8.5          70
8  14.0          8         455.0        225    4425          10.0          70
9  15.0          8         390.0        190    3850           8.5          70

In [12]:
df_clean.describe()

,mpg,cylinders,displacement,weight,acceleration,model year
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000

In [13]:
# Get all column names
df_clean.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year'],
      dtype='str')

In [14]:
df_clean.columns.to_list()

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'model year']

In [15]:
TARGET = 'mpg'
quan_candidates = ['displacement', 'horsepower', 'weight', 'acceleration', 'model year']

In [16]:
df_clean[TARGET]

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [17]:
df_clean[quan_candidates]

     displacement horsepower  weight  acceleration  model year
0           307.0        130    3504          12.0          70
1           350.0        165    3693          11.5          70
2           318.0        150    3436          11.0          70
3           304.0        150    3433          12.0          70
4           302.0        140    3449          10.5          70
..            ...        ...     ...           ...         ...
393         140.0         86    2790          15.6          82
394          97.0         52    2130          24.6          82
395         135.0         84    2295          11.6          82
396         120.0         79    2625          18.6          82
397         119.0         82    2720          19.4          82

[398 rows x 5 columns]